---
apiVersion: v1
kind: Namespace
metadata:
  name: blog-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-sa
  namespace: blog-ns

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: blog
  namespace: blog-ns
  labels:
    k8s-app: blog
    version: v0
spec:
  replicas: 1
  selector:
    k8s-app: blog
    version: v0
  template:
    metadata:
      labels:
        k8s-app: blog
        version: v0
    spec:
      serviceAccountName: blog-sa
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
      containers:
      - name: ghostunnel
        image: localhost/spiffe/ghostunnel:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
        env:
        - name: AGENT_SOCKET
          value: /tmp/spire/agent.sock
        - name: LISTEN
          value: 127.0.0.1:3306
        - name: UPSTREAM
          value: 10.90.0.20:33306
        volumeMounts:
        - name: spire-socket
          mountPath: /tmp/spire
        ports:
        - containerPort: 3306
          name: ghostunnel
          protocol: TCP
      - name: blog
        image: localhost/spiffe/blog:latest
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
        env:
        - name: BLOG_DATABASE
          value: 127.0.0.1:3306
        - name: BLOG_HOST
          value: 10.90.0.10:30080
        - name: BLOG_USER
          value: dbuser
        - name: BLOG_PASS
          value: badpass
        ports:
        - containerPort: 8080
          name: blog
          protocol: TCP
      volumes:
      - name: spire-socket
        hostPath:
          path: /tmp

---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: blog-ns
  labels:
    k8s-app: blog
spec:
  selector:
    k8s-app: blog
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080

