server:
  port: 4000
  ssl:
      key-store:
      key-store-password:
      key-store-type: Spiffe
      enabled: true
      client-auth: need
  http:
      port: 4001

tasks:
  service: https://backend:3000/tasks/
