---

language: go

sudo: required
dist: trusty

services:
  - docker

go:
  - 1.9

deploy:
  - provider: releases
    api_key:
      secure: 'rxcM8Ttmo0zTd2i+NBgG6YIDwtRwNCL28vPvAQ4GZ/SS7+8/fZn1RF8ZI2wWbZB2SqQveAiPmO66ZPXcGDsf/ynOHVvppn7IwJRSJoh2Z+QNu5i97JqQEtcM3DY5DZKO+scYqeCvINmLXmwSLHYDij/Nnu0hBXeobPizBDhqnN7AD0FZq2zbbCxZFPrAwUsB1G6wZTKWRFl4lX7baKDqyICc6OgGzb3m127SgrseW2zR6vBfHbc3Ep1hoIqjTf0vVXyDhCpDaIXAkZP43Jp1FxBwryrhEtPzx/46KWvPJLRwZc5gnRRrXX0HqrhlD577OxE/8VnjI+32mRTTNjSD8aOBraZ1Q71U5uLXLMoL1LD3qAfYv5sJaUKdbGtDkfGGwQ4X70A97gqmQI5gpYWU1LUksHwVJMwUqO2cPWciQikOTXQrDUT3qnuauZ432IP7izNhYmFWYwOEoQOzUA8pF1dl2jvUURY9dgQ2AHcJfCYV9C5TnBQ/2nO4Xbc96eo/Ky5OIX+lsfHx4bJmqvT6N+o/b9TJQYg3o4t0rqGB95Zt8/SbapvKlIU5I8SKGyuEpnKN4yUGAQRg8heuAPJ8mz3bmGriT9oC3q577vAqaCm2JcmvHCVx9OME0B04vLzxjYJXPHAi9CRmhUOZ8haHby3BkI3KYjnAaasUBot7oPI='
    file:
      - ghostunnel-${TRAVIS_TAG}-linux-amd64-with-pkcs11
      - ghostunnel-${TRAVIS_TAG}-darwin-amd64-without-pkcs11
      - ghostunnel-${TRAVIS_TAG}-freebsd-amd64-without-pkcs11
      - ghostunnel-${TRAVIS_TAG}-linux-amd64-with-pkcs11.sha256sum
      - ghostunnel-${TRAVIS_TAG}-darwin-amd64-without-pkcs11.sha256sum
      - ghostunnel-${TRAVIS_TAG}-freebsd-amd64-without-pkcs11.sha256sum
    draft: true
    skip_cleanup: true
    on:
      tags: true
      go: 1.9

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - go get github.com/mattn/goveralls

install:
  - CGO_ENABLED=0 go build -o ghostunnel-${TRAVIS_TAG}-linux-amd64-without-pkcs11 .
  - CGO_ENABLED=1 go build -o ghostunnel-${TRAVIS_TAG}-linux-amd64-with-pkcs11 .
  - GOOS=darwin CGO_ENABLED=0 go build -o ghostunnel-${TRAVIS_TAG}-darwin-amd64-without-pkcs11 .
  - GOOS=freebsd CGO_ENABLED=0 go build -o ghostunnel-${TRAVIS_TAG}-freebsd-amd64-without-pkcs11 .
  - 'for file in ghostunnel-${TRAVIS_TAG}-*; do sha256sum ${file} > ${file}.sha256sum; done'
  - make docker-build

script:
  - GO_VERSION=${TRAVIS_GO_VERSION} make docker-test

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile coverage-merged.out -service=travis-ci
